In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [13]:
#2D
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]],dtype='int8')
print(b)
print(b.shape)
print(b.size)
print(b.ndim)
print(b.dtype)
print(b.itemsize) # just one byte to item
print(b.nbytes)

[[9 8 7]
 [6 5 4]]
(2, 3)
6
2
int8
1
6


In [15]:
### Accessing/Changing specific elements, rows, columns, etc
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]],dtype='int8')
b[1,2]

4

In [16]:
b[:,2]

array([7, 4], dtype=int8)

In [17]:
b[1,:]

array([6, 5, 4], dtype=int8)

In [19]:
b[1,0:-1:2] #0 FOR START , 1 FOR END,2 FOR STEP

array([6], dtype=int8)

In [21]:
b[1,2]=20
print(b)

[[ 9  8  7]
 [ 6  5 20]]


In [22]:
b[:,2]=[3,4]
print(b)

[[9 8 3]
 [6 5 4]]


In [31]:
#3d
c=np.array([[[1,2],[3,4]],[[1,2],[3,4]]])
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
c[1,1,1]

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]
3
(2, 2, 2)
8


4

In [39]:
#replace
c=np.array([[[1,2],[3,4]],[[1,2],[3,4]]])
c[0,:,:]=[[1,2],[99,12]]
print(c)

[[[ 1  2]
  [99 12]]

 [[ 1  2]
  [ 3  4]]]


In [41]:
x=np.zeros((2,2))
x

array([[0., 0.],
       [0., 0.]])

In [46]:
x=np.ones((2,2,2),dtype='int8')
x

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int8)

In [49]:
e=np.full((2,3,3),6)
e

array([[[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]],

       [[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]]])

In [51]:
# Any other number (full_like)
t=np.full_like(e,12)
t

array([[[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]],

       [[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]]])

In [56]:
# Random decimal numbers between 0 and 1
np.random.rand(4,2)

array([[0.32575648, 0.37536898],
       [0.67675322, 0.19756112],
       [0.29081119, 0.33127174],
       [0.51574958, 0.5622728 ]])

In [58]:
# Random  numbers
np.random.randint(-4,2,(2,2))

array([[ 1,  1],
       [-2, -3]])

In [59]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [63]:
h=np.repeat(t,2,axis=0) # axis 1 for row
h

array([[[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]],

       [[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]],

       [[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]],

       [[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]]])

In [73]:
q=np.array([[1,2,3,5],[1,5,8,9]])
#q
k=np.copy(q)
k[0,1]=99
print(k)
print(q)

[[ 1 99  3  5]
 [ 1  5  8  9]]
[[1 2 3 5]
 [1 5 8 9]]


In [74]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [75]:
a+2

array([3, 4, 5, 6])

In [76]:
a-2

array([-1,  0,  1,  2])

In [77]:
a*2

array([2, 4, 6, 8])

In [78]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [79]:
a

array([1, 2, 3, 4])

In [80]:
k=np.array([1,2,3,4])

In [82]:
z=np.matmul(a,k)
z

30